// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUint is reflected uint.
var typUint = reflect.TypeFor[uint]()

// AnyToUint converts the given value to uint
// using the package-level registry.
func AnyToUint(value any, opts ...Option) (uint, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUint)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "uint").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uint), nil // nolint: forcetypeassert
}
