// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/convert/internal/test"
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_AnyToUint8_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		want  uint8
		err   error
		msg   string
	}{
		{"success from float64", 42.0, 42, nil, ""},
		{
			"error - undefined conversion",
			test.Type{},
			0,
			ErrUnkConv,
			"conversion undefined: from test.Type to uint8",
		},
		{
			"error - range",
			-1,
			0,
			ErrInvRange,
			"value out of range: from int to uint8",
		},
		{
			"error - fraction",
			4.2,
			0,
			ErrFraction,
			"must be a whole number: from float64 to uint8",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToUint8(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint8(0), have)
		})
	}
}
