// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
	"time"
)

// typDuration is the [reflect.Type] of [time.Duration].
var typDuration = reflect.TypeFor[time.Duration]()

// AnyToDuration converts the given value to [time.Duration]
// using the package-level registry.
func AnyToDuration(value any, opts ...Option) (time.Duration, error) {
	ops := NewOptions(opts...)
	dst := "time.Duration"
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, dst).Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typDuration)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, dst).Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, ChangeErrDstName(err, dst)
	}
	return ret.(time.Duration), nil //nolint:forcetypeassert
}
