// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/convert/internal/test"
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_AnyToFloat64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		want  float64
		err   error
		msg   string
	}{
		{"success from integer", 42, 42.0, nil, ""},
		{
			"error - undefined conversion",
			test.Type{},
			0,
			ErrUnkConv,
			"conversion undefined: from test.Type to float64",
		},
		{
			"error - safe overflow",
			Float64SafeIntMax + 1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from int to float64",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToFloat64(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float64(0), have)
		})
	}
}
