// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"net/http"
	"testing"
)

func Test_AnyToRune_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		want  rune
		err   error
		msg   string
	}{
		{"success from float64", 42.0, 42, nil, ""},
		{
			"error - undefined conversion",
			http.Cookie{},
			0,
			ErrUnkConv,
			"conversion undefined: from http.Cookie to rune",
		},
		{
			"error - fraction",
			4.2,
			0,
			ErrFraction,
			"must be a whole number: from float64 to rune",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToRune(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, rune(0), have)
		})
	}
}
