// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typFloat64 is the [reflect.Type] of float64.
var typFloat64 = reflect.TypeFor[float64]()

// AnyToFloat64 converts the given value to float64
// using the package-level registry.
func AnyToFloat64(value any, opts ...Option) (float64, error) {
	ops := NewOptions(opts...)
	dst := "float64"
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, dst).Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typFloat64)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, dst).Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(float64), nil //nolint:forcetypeassert
}
