// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typInt64 is reflected int64.
var typInt64 = reflect.TypeFor[int64]()

// AnyToInt64 converts the given value to int64
// using the package-level registry.
func AnyToInt64(value any, opts ...Option) (int64, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typInt64)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "int64").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(int64), nil // nolint: forcetypeassert
}
