// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUint16 is reflected uint16.
var typUint16 = reflect.TypeFor[uint16]()

// AnyToUint16 converts the given value to uint16
// using the package-level registry.
func AnyToUint16(value any, opts ...Option) (uint16, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUint16)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "uint16").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uint16), nil // nolint: forcetypeassert
}
