// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUint16 is the [reflect.Type] of uint16.
var typUint16 = reflect.TypeFor[uint16]()

// AnyToUint16 converts the given value to uint16
// using the package-level registry.
func AnyToUint16(value any, opts ...Option) (uint16, error) {
	ops := NewOptions(opts...)
	dst := "uint16"
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, dst).Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUint16)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, dst).Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uint16), nil //nolint:forcetypeassert
}
