// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typInt8 is the [reflect.Type] of int8.
var typInt8 = reflect.TypeFor[int8]()

// AnyToInt8 converts the given value to int8
// using the package-level registry.
func AnyToInt8(value any, opts ...Option) (int8, error) {
	ops := NewOptions(opts...)
	dst := "int8"
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, dst).Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typInt8)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, dst).Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(int8), nil //nolint:forcetypeassert
}
