// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typRune is reflected rune.
var typRune = reflect.TypeFor[rune]()

// AnyToRune converts the given value to rune
// using the package-level registry.
func AnyToRune(value any, opts ...Option) (rune, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typRune)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "rune").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, ChangeErrDstName(err, "rune")
	}
	return ret.(rune), nil // nolint: forcetypeassert
}
