// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
	"time"
)

// typDuration is reflected [time.Duration].
var typDuration = reflect.TypeFor[time.Duration]()

// AnyToDuration converts the given value to [time.Duration]
// using the package-level registry.
func AnyToDuration(value any, opts ...Option) (time.Duration, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typDuration)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "time.Duration").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, ChangeErrDstName(err, "time.Duration")
	}
	return ret.(time.Duration), nil // nolint: forcetypeassert
}
