// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typInt32 is reflected int32.
var typInt32 = reflect.TypeFor[int32]()

// AnyToInt32 converts the given value to int32
// using the package-level registry.
func AnyToInt32(value any, opts ...Option) (int32, error) {
	ops := NewOptions(opts...)
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, "int32").Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typInt32)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, "int32").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(int32), nil // nolint: forcetypeassert
}
