// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUint32 is reflected uint32.
var typUint32 = reflect.TypeFor[uint32]()

// AnyToUint32 converts the given value to uint32
// using the package-level registry.
func AnyToUint32(value any, opts ...Option) (uint32, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUint32)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "uint32").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uint32), nil // nolint: forcetypeassert
}
