// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typByte is reflected byte.
var typByte = reflect.TypeFor[byte]()

// AnyToByte converts the given value to byte
// using the package-level registry.
func AnyToByte(value any, opts ...Option) (byte, error) {
	ops := NewOptions(opts...)
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typByte)
	if wrp == nil {
		format := "%v: from %T to %v"
		return 0, NewError(ErrUnkConv, value, "byte").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, ChangeErrDstName(err, "byte")
	}
	return ret.(byte), nil // nolint: forcetypeassert
}
