// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typInt16 is reflected int16.
var typInt16 = reflect.TypeFor[int16]()

// AnyToInt16 converts the given value to int16
// using the package-level registry.
func AnyToInt16(value any, opts ...Option) (int16, error) {
	ops := NewOptions(opts...)
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, "int16").Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typInt16)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, "int16").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(int16), nil // nolint: forcetypeassert
}
