// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/convert/internal/test"
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_AnyToByte(t *testing.T) {
	t.Run("error - nil registry", func(t *testing.T) {
		// --- Given ---
		opt := WithRegistry(nil)

		// --- When ---
		have, err := AnyToByte(42, opt)

		// --- Then ---
		assert.ErrorIs(t, ErrNilRegistry, err)
		assert.ErrorEqual(t, "nil registry: from int to byte", err)
		assert.Equal(t, byte(0), have)
	})
}

func Test_AnyToByte_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		want  byte
	}{
		{"success from float64", 42.0, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToByte(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
		})
	}
}

func Test_AnyToByte_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		err   error
		msg   string
	}{
		{
			"error - undefined conversion",
			test.Type{},
			ErrUnkConv,
			"conversion undefined: from test.Type to byte",
		},
		{
			"error - range",
			-1,
			ErrInvRange,
			"value out of range: from int to byte",
		},
		{
			"error - fraction",
			4.2,
			ErrFraction,
			"must be a whole number: from float64 to byte",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToByte(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, byte(0), have)
		})
	}
}
