// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUint8 is the [reflect.Type] of uint8.
var typUint8 = reflect.TypeFor[uint8]()

// AnyToUint8 converts the given value to uint8
// using the package-level registry.
func AnyToUint8(value any, opts ...Option) (uint8, error) {
	ops := NewOptions(opts...)
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, "uint8").Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUint8)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, "uint8").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uint8), nil //nolint:forcetypeassert
}
