// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typInt is the [reflect.Type] of int.
var typInt = reflect.TypeFor[int]()

// AnyToInt converts the given value to int
// using the package-level registry.
func AnyToInt(value any, opts ...Option) (int, error) {
	ops := NewOptions(opts...)
	dst := "int"
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, dst).Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typInt)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, dst).Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(int), nil //nolint:forcetypeassert
}
