// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/convert/internal/test"
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_AnyToFloat64(t *testing.T) {
	t.Run("error - nil registry", func(t *testing.T) {
		// --- Given ---
		opt := WithRegistry(nil)

		// --- When ---
		have, err := AnyToFloat64(42, opt)

		// --- Then ---
		assert.ErrorIs(t, ErrNilRegistry, err)
		assert.ErrorEqual(t, "nil registry: from int to float64", err)
		assert.Equal(t, float64(0), have)
	})
}

func Test_AnyToFloat64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		want  float64
	}{
		{"success from integer", 42, 42.0},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToFloat64(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
		})
	}
}

func Test_AnyToFloat64_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value any
		err   error
		msg   string
	}{
		{
			"error - undefined conversion",
			test.Type{},
			ErrUnkConv,
			"conversion undefined: from test.Type to float64",
		},
		{
			"error - safe overflow",
			int64(Float64SafeIntMax) + 1,
			ErrInvSafeRange,
			"value out of safe range: from int64 to float64",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := AnyToFloat64(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float64(0), have)
		})
	}
}
