// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"reflect"
)

// typUintptr is reflected uintptr.
var typUintptr = reflect.TypeFor[uintptr]()

// AnyToUintptr converts the given value to uintptr
// using the package-level registry.
func AnyToUintptr(value any, opts ...Option) (uintptr, error) {
	ops := NewOptions(opts...)
	format := "%v: from %T to %v"
	if ops.reg == nil {
		return 0, NewError(ErrNilRegistry, value, "uintptr").Format(format)
	}
	src := reflect.TypeOf(value)
	wrp := ops.reg.lookup(src, typUintptr)
	if wrp == nil {
		return 0, NewError(ErrUnkConv, value, "uintptr").Format(format)
	}
	ret, err := wrp.cst(value)
	if err != nil {
		return 0, err
	}
	return ret.(uintptr), nil //nolint:forcetypeassert
}
