// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToInt64 safely converts byte value to int64.
func ByteToInt64(src byte) (dst int64, err error) {
	return int64(src), nil
}
