// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToInt safely converts byte value to int.
func ByteToInt(src byte) (dst int, err error) {
	return int(src), nil
}
