// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToUint8 safely converts byte value to uint8.
func ByteToUint8(src byte) (dst uint8, err error) {
	return uint8(src), nil
}
