// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToUint32 safely converts byte value to uint32.
func ByteToUint32(src byte) (dst uint32, err error) {
	return uint32(src), nil
}
