// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_ByteToByte_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value byte
		want  byte
	}{
		{"min", 0, 0},
		{"max", math.MaxUint8, math.MaxUint8},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := ByteToByte(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, byte(have))
		})
	}
}
