// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToFloat32 safely converts byte value to float32.
func ByteToFloat32(src byte) (dst float32, err error) {
	return float32(src), nil
}
