// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToByte safely converts byte value to byte.
func ByteToByte(src byte) (dst byte, err error) {
	return src, nil
}
