// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToUint64 safely converts byte value to uint64.
func ByteToUint64(src byte) (dst uint64, err error) {
	return uint64(src), nil
}
