// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// ByteToDuration safely converts byte value to [time.Duration].
func ByteToDuration(src byte) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
