// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToInt32 safely converts byte value to int32.
func ByteToInt32(src byte) (dst int32, err error) {
	return int32(src), nil
}
