// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToUint safely converts byte value to uint.
func ByteToUint(src byte) (dst uint, err error) {
	return uint(src), nil
}
