// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// ByteToInt8 safely converts byte value to int8.
func ByteToInt8(src byte) (dst int8, err error) {
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "byte", "int8")
	}
	return int8(src), nil
}
