// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToRune safely converts byte value to rune.
func ByteToRune(src byte) (dst rune, err error) {
	return rune(src), nil
}
