// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToFloat64 safely converts byte value to float64.
func ByteToFloat64(src byte) (dst float64, err error) {
	return float64(src), nil
}
