// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToInt16 safely converts byte value to int16.
func ByteToInt16(src byte) (dst int16, err error) {
	return int16(src), nil
}
