// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// ByteToUint16 safely converts byte value to uint16.
func ByteToUint16(src byte) (dst uint16, err error) {
	return uint16(src), nil
}
