// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToInt safely converts a [time.Duration] value to int.
func DurationToInt(src time.Duration) (dst int, err error) {
	if src < math.MinInt {
		return 0, NewError(ErrInvRange, "time.Duration", "int")
	}
	if src > math.MaxInt {
		return 0, NewError(ErrInvRange, "time.Duration", "int")
	}
	return int(src), nil
}
