// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToUint16 safely converts [time.Duration] value to uint16.
func DurationToUint16(src time.Duration) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint16")
	}
	return uint16(src), nil
}
