// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToUint64 safely converts [time.Duration] value to uint64.
func DurationToUint64(src time.Duration) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint64")
	}
	return uint64(src), nil
}
