// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToInt64 safely converts [time.Duration] value to int64.
func DurationToInt64(src time.Duration) (dst int64, err error) {
	return int64(src), nil
}
