// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToInt32 safely converts [time.Duration] value to int32.
func DurationToInt32(src time.Duration) (dst int32, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "time.Duration", "int32")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "time.Duration", "int32")
	}
	return int32(src), nil
}
