// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToInt8 safely converts [time.Duration] value to int8.
func DurationToInt8(src time.Duration) (dst int8, err error) {
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "time.Duration", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "time.Duration", "int8")
	}
	return int8(src), nil
}
