// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToUint32 safely converts [time.Duration] value to uint32.
func DurationToUint32(src time.Duration) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint32")
	}
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint32")
	}
	return uint32(src), nil
}
