// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
	"time"
)

func Test_DurationToInt8_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value time.Duration
		want  int8
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := DurationToInt8(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, time.Duration(have))
		})
	}
}

func Test_DurationToInt8_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value time.Duration
		err   error
		msg   string
	}{
		{
			"error - underflow",
			math.MinInt8 - 1,
			ErrInvRange,
			"value out of range: from time.Duration to int8",
		},
		{
			"error - overflow",
			math.MaxInt8 + 1,
			ErrInvRange,
			"value out of range: from time.Duration to int8",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := DurationToInt8(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, int8(0), have)
		})
	}
}
