// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToInt16 safely converts [time.Duration] value to int16.
func DurationToInt16(src time.Duration) (dst int16, err error) {
	if src < math.MinInt16 {
		return 0, NewError(ErrInvRange, "time.Duration", "int16")
	}
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "time.Duration", "int16")
	}
	return int16(src), nil
}
