// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToDuration safely converts [time.Duration] value to [time.Duration].
func DurationToDuration(src time.Duration) (dst time.Duration, err error) {
	return src, nil
}
