// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToByte safely converts [time.Duration] value to byte.
func DurationToByte(src time.Duration) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "time.Duration", "byte")
	}
	return byte(src), nil
}
