// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToUintptr safely converts [time.Duration] value to uintptr.
func DurationToUintptr(src time.Duration) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uintptr")
	}
	return uintptr(src), nil
}
