// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToFloat64 safely converts [time.Duration] value to float64.
func DurationToFloat64(src time.Duration) (dst float64, err error) {
	if src < Float64SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "time.Duration", "float64")
	}
	if src > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "time.Duration", "float64")
	}
	return float64(src), nil
}
