// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"strconv"
	"testing"
	"time"
)

func Test_DurationToUint_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value time.Duration
		want  uint
		err   error
		msg   string
	}{
		{
			"error - negative",
			-1,
			0,
			ErrInvRange,
			"value out of range: from time.Duration to uint",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := DurationToUint(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, time.Duration(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint(0), have)
		})
	}
}

func Test_DurationToUint_32bit_tabular(t *testing.T) {
	if strconv.IntSize != 32 {
		t.Skip("32-bit platforms only")
	}

	tt := []struct {
		testN string

		value time.Duration
		want  uint
		err   error
		msg   string
	}{
		{
			"error - overflow",
			math.MaxUint32 + 1,
			0,
			ErrInvRange,
			"value out of range: from time.Duration to uint",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := DurationToUint(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, tc.want, have)
		})
	}
}
