// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToRune safely converts [time.Duration] value to rune.
func DurationToRune(src time.Duration) (dst rune, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "time.Duration", "rune")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "time.Duration", "rune")
	}
	return rune(src), nil
}
