// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToFloat32 safely converts [time.Duration] value to float32.
func DurationToFloat32(src time.Duration) (dst float32, err error) {
	if src < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "time.Duration", "float32")
	}
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "time.Duration", "float32")
	}
	return float32(src), nil
}
