// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// DurationToUint8 safely converts [time.Duration] value to uint8.
func DurationToUint8(src time.Duration) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint8")
	}
	return uint8(src), nil
}
