// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToInt safely converts [time.Duration] value to int.
func DurationToInt(src time.Duration) (dst int, err error) {
	return int(src), nil
}
