// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// DurationToUint safely converts [time.Duration] value to uint.
func DurationToUint(src time.Duration) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "time.Duration", "uint")
	}
	return uint(src), nil
}
