// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
	"time"
)

func Test_Float64ToDuration_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value float64
		want  time.Duration
		err   error
		msg   string
	}{
		{
			"error - must be a number",
			math.NaN(),
			0,
			ErrInvValue,
			"invalid value: from float64 to time.Duration",
		},
		{
			"error - negative infinity",
			math.Inf(-1),
			0,
			ErrInvValue,
			"invalid value: from float64 to time.Duration",
		},
		{
			"error - positive infinity",
			math.Inf(1),
			0,
			ErrInvValue,
			"invalid value: from float64 to time.Duration",
		},
		{
			"error - fraction",
			4.2,
			0,
			ErrFraction,
			"must be a whole number: from float64 to time.Duration",
		},
		{
			"error - safe underflow",
			Float64SafeIntMin - 1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from float64 to time.Duration",
		},
		{
			"error - safe overflow",
			Float64SafeIntMax + 1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from float64 to time.Duration",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Float64ToDuration(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, float64(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, time.Duration(0), have)
		})
	}
}
