// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToInt8 safely converts float32 value to int8.
func Float32ToInt8(src float32) (dst int8, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "int8")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "int8")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "int8")
	}
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "float32", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "float32", "int8")
	}
	return int8(src), nil
}
