// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToRune safely converts float64 value to rune.
func Float64ToRune(src float64) (dst rune, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "rune")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "rune")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "rune")
	}
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "float64", "rune")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "float64", "rune")
	}
	return rune(src), nil
}
