// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_Float64ToFloat32(t *testing.T) {
	t.Run("NaN", func(t *testing.T) {
		// --- Given ---
		src := math.NaN()

		// --- When ---
		have, err := Float64ToFloat32(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsNaN(float64(have)))
	})

	t.Run("positive infinity", func(t *testing.T) {
		// --- Given ---
		src := math.Inf(1)

		// --- When ---
		have, err := Float64ToFloat32(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsInf(float64(have), 1))
	})

	t.Run("negative infinity", func(t *testing.T) {
		// --- Given ---
		src := math.Inf(-1)

		// --- When ---
		have, err := Float64ToFloat32(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsInf(float64(have), -1))
	})
}

func Test_Float64ToFloat32_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value float64
		want  float32
		err   error
		msg   string
	}{
		{
			"error - overflow",
			math.MaxFloat64,
			0,
			ErrInvRange,
			"value out of range: from float64 to float32",
		},
		{
			"error - negative overflow",
			-math.MaxFloat64,
			0,
			ErrInvRange,
			"value out of range: from float64 to float32",
		},
		{
			"error - precision loss",
			0.1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from float64 to float32",
		},
		{"fraction", 0.5, 0.5, nil, ""},
		{"large", 1e10, 1e10, nil, ""},
		{"max", math.MaxFloat32, math.MaxFloat32, nil, ""},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Float64ToFloat32(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, float64(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float32(0), have)
		})
	}
}
