// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToUint32 safely converts float32 value to uint32.
func Float32ToUint32(src float32) (dst uint32, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "uint32")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "uint32")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "uint32")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float32", "uint32")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float32", "uint32")
	}
	return uint32(src), nil
}
