// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Float32ToFloat32 safely converts float32 value to float32.
func Float32ToFloat32(src float32) (dst float32, err error) {
	return src, nil
}
