// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToFloat32 safely converts float64 value to float32.
func Float64ToFloat32(src float64) (dst float32, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "float32")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "float32")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "float32")
	}
	if f64 < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "float64", "float32")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float64", "float32")
	}
	return float32(src), nil
}
