// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// Float32ToDuration safely converts float32 value to [time.Duration].
func Float32ToDuration(src float32) (dst time.Duration, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "time.Duration")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "time.Duration")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "time.Duration")
	}
	if f64 < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "float32", "time.Duration")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float32", "time.Duration")
	}
	return time.Duration(src), nil
}
