// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToUint16 safely converts float32 value to uint16.
func Float32ToUint16(src float32) (dst uint16, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "uint16")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "uint16")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "uint16")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float32", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "float32", "uint16")
	}
	return uint16(src), nil
}
