// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToUintptr safely converts float64 value to uintptr.
func Float64ToUintptr(src float64) (dst uintptr, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "uintptr")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "uintptr")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "uintptr")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "uintptr")
	}
	if f64 > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float64", "uintptr")
	}
	return uintptr(src), nil
}
