// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToInt64 safely converts float32 value to int64.
func Float32ToInt64(src float32) (dst int64, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "int64")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "int64")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "int64")
	}
	if f64 < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "float32", "int64")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float32", "int64")
	}
	return int64(src), nil
}
