// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToUint8 safely converts float32 value to uint8.
func Float32ToUint8(src float32) (dst uint8, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "uint8")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "uint8")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "uint8")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float32", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "float32", "uint8")
	}
	return uint8(src), nil
}
