// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_Float64ToUint32_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value float64
		want  uint32
		err   error
		msg   string
	}{
		{
			"error - must be a number",
			math.NaN(),
			0,
			ErrInvValue,
			"invalid value: from float64 to uint32",
		},
		{
			"error - negative infinity",
			math.Inf(-1),
			0,
			ErrInvValue,
			"invalid value: from float64 to uint32",
		},
		{
			"error - positive infinity",
			math.Inf(1),
			0,
			ErrInvValue,
			"invalid value: from float64 to uint32",
		},
		{
			"error - fraction",
			4.2,
			0,
			ErrFraction,
			"must be a whole number: from float64 to uint32",
		},
		{
			"error - negative",
			-1,
			0,
			ErrInvRange,
			"value out of range: from float64 to uint32",
		},
		{
			"error - overflow",
			math.MaxUint32 + 1,
			0,
			ErrInvRange,
			"value out of range: from float64 to uint32",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Float64ToUint32(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, float64(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint32(0), have)
		})
	}
}
