// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Float32ToFloat64 safely converts float32 value to float64.
func Float32ToFloat64(src float32) (dst float64, err error) {
	return float64(src), nil
}
