// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToFloat32 safely converts a float64 value to float32.
func Float64ToFloat32(src float64) (dst float32, err error) {
	if !math.IsInf(src, 0) && math.Abs(src) > math.MaxFloat32 {
		return 0, NewError(ErrInvRange, "float64", "float32")
	}
	if !math.IsNaN(src) && float64(float32(src)) != src {
		return 0, NewError(ErrInvSafeRange, "float64", "float32")
	}
	return float32(src), nil
}
