// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToUint32 safely converts float64 value to uint32.
func Float64ToUint32(src float64) (dst uint32, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "uint32")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "uint32")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "uint32")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "uint32")
	}
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "float64", "uint32")
	}
	return uint32(src), nil
}
