// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToByte safely converts float64 value to byte.
func Float64ToByte(src float64) (dst byte, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "byte")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "byte")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "byte")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "float64", "byte")
	}
	return byte(src), nil
}
