// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToUint safely converts float64 value to uint.
func Float64ToUint(src float64) (dst uint, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "uint")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "uint")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "uint")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "uint")
	}
	if f64 > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float64", "uint")
	}
	return uint(src), nil
}
