// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToUint8 safely converts float64 value to uint8.
func Float64ToUint8(src float64) (dst uint8, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "uint8")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "uint8")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "uint8")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "float64", "uint8")
	}
	return uint8(src), nil
}
