// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToRune safely converts float32 value to rune.
func Float32ToRune(src float32) (dst rune, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "rune")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "rune")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "rune")
	}
	if f64 < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "float32", "rune")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float32", "rune")
	}
	return rune(src), nil
}
