// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_Float32ToFloat64(t *testing.T) {
	t.Run("NaN", func(t *testing.T) {
		// --- Given ---
		src := float32(math.NaN())

		// --- When ---
		have, err := Float32ToFloat64(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsNaN(float64(have)))
	})

	t.Run("positive infinity", func(t *testing.T) {
		// --- Given ---
		src := float32(math.Inf(1))

		// --- When ---
		have, err := Float32ToFloat64(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsInf(float64(have), 1))
	})

	t.Run("negative infinity", func(t *testing.T) {
		// --- Given ---
		src := float32(math.Inf(-1))

		// --- When ---
		have, err := Float32ToFloat64(src)

		// --- Then ---
		assert.NoError(t, err)
		assert.True(t, math.IsInf(float64(have), -1))
	})
}

func Test_Float32ToFloat64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value float32
		want  float64
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Float32ToFloat64(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, float32(have))
		})
	}
}
