// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToUint16 safely converts float64 value to uint16.
func Float64ToUint16(src float64) (dst uint16, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "uint16")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "uint16")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "uint16")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float64", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "float64", "uint16")
	}
	return uint16(src), nil
}
