// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToUintptr safely converts float32 value to uintptr.
func Float32ToUintptr(src float32) (dst uintptr, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "uintptr")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "uintptr")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "uintptr")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float32", "uintptr")
	}
	if f64 > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float32", "uintptr")
	}
	return uintptr(src), nil
}
