// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToInt8 safely converts float64 value to int8.
func Float64ToInt8(src float64) (dst int8, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "int8")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "int8")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "int8")
	}
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "float64", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "float64", "int8")
	}
	return int8(src), nil
}
