// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float64ToInt16 safely converts float64 value to int16.
func Float64ToInt16(src float64) (dst int16, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "int16")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "int16")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "int16")
	}
	if src < math.MinInt16 {
		return 0, NewError(ErrInvRange, "float64", "int16")
	}
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "float64", "int16")
	}
	return int16(src), nil
}
