// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Float64ToFloat64 safely converts float64 value to float64.
func Float64ToFloat64(src float64) (dst float64, err error) {
	return src, nil
}
