// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Float32ToByte safely converts float32 value to byte.
func Float32ToByte(src float32) (dst byte, err error) {
	f64 := float64(src)
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float32", "byte")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float32", "byte")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float32", "byte")
	}
	if src < 0 {
		return 0, NewError(ErrInvRange, "float32", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "float32", "byte")
	}
	return byte(src), nil
}
