// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// Float64ToDuration safely converts float64 value to [time.Duration].
func Float64ToDuration(src float64) (dst time.Duration, err error) {
	f64 := src
	if math.IsNaN(f64) {
		return 0, NewError(ErrInvValue, "float64", "time.Duration")
	}
	if math.IsInf(f64, 0) {
		return 0, NewError(ErrInvValue, "float64", "time.Duration")
	}
	if f64 != math.Trunc(f64) {
		return 0, NewError(ErrFraction, "float64", "time.Duration")
	}
	if f64 < Float64SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "float64", "time.Duration")
	}
	if f64 > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "float64", "time.Duration")
	}
	return time.Duration(src), nil
}
