// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToInt64 safely converts int16 value to int64.
func Int16ToInt64(src int16) (dst int64, err error) {
	return int64(src), nil
}
