// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int16ToByte safely converts int16 value to byte.
func Int16ToByte(src int16) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int16", "byte")
	}
	return byte(src), nil
}
