// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToUint32 safely converts int16 value to uint32.
func Int16ToUint32(src int16) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uint32")
	}
	return uint32(src), nil
}
