// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Int16ToDuration safely converts int16 value to [time.Duration].
func Int16ToDuration(src int16) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
