// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToFloat64 safely converts int16 value to float64.
func Int16ToFloat64(src int16) (dst float64, err error) {
	return float64(src), nil
}
