// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToInt16 safely converts int16 value to int16.
func Int16ToInt16(src int16) (dst int16, err error) {
	return src, nil
}
