// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int16ToUint8 safely converts int16 value to uint8.
func Int16ToUint8(src int16) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int16", "uint8")
	}
	return uint8(src), nil
}
