// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToInt32 safely converts int16 value to int32.
func Int16ToInt32(src int16) (dst int32, err error) {
	return int32(src), nil
}
