// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToFloat32 safely converts int16 value to float32.
func Int16ToFloat32(src int16) (dst float32, err error) {
	return float32(src), nil
}
