// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToRune safely converts int16 value to rune.
func Int16ToRune(src int16) (dst rune, err error) {
	return rune(src), nil
}
