// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToUint16 safely converts int16 value to uint16.
func Int16ToUint16(src int16) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uint16")
	}
	return uint16(src), nil
}
