// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToUintptr safely converts int16 value to uintptr.
func Int16ToUintptr(src int16) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uintptr")
	}
	return uintptr(src), nil
}
