// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToInt safely converts int16 value to int.
func Int16ToInt(src int16) (dst int, err error) {
	return int(src), nil
}
