// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToUint safely converts int16 value to uint.
func Int16ToUint(src int16) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uint")
	}
	return uint(src), nil
}
