// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int16ToUint64 safely converts int16 value to uint64.
func Int16ToUint64(src int16) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int16", "uint64")
	}
	return uint64(src), nil
}
