// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_Int32ToUint_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int32
		want  uint
		err   error
		msg   string
	}{
		{
			"error - negative",
			-1,
			0,
			ErrInvRange,
			"value out of range: from int32 to uint",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Int32ToUint(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, int32(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint(0), have)
		})
	}
}
