// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int32ToUint8 safely converts int32 value to uint8.
func Int32ToUint8(src int32) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int32", "uint8")
	}
	return uint8(src), nil
}
