// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToInt64 safely converts int32 value to int64.
func Int32ToInt64(src int32) (dst int64, err error) {
	return int64(src), nil
}
