// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToRune safely converts int32 value to rune.
func Int32ToRune(src int32) (dst rune, err error) {
	return rune(src), nil
}
