// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToInt safely converts int32 value to int.
func Int32ToInt(src int32) (dst int, err error) {
	return int(src), nil
}
