// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToInt32 safely converts int32 value to int32.
func Int32ToInt32(src int32) (dst int32, err error) {
	return src, nil
}
