// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int32ToInt16 safely converts int32 value to int16.
func Int32ToInt16(src int32) (dst int16, err error) {
	if src < math.MinInt16 {
		return 0, NewError(ErrInvRange, "int32", "int16")
	}
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "int32", "int16")
	}
	return int16(src), nil
}
