// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToUintptr safely converts int32 value to uintptr.
func Int32ToUintptr(src int32) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "uintptr")
	}
	return uintptr(src), nil
}
