// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToUint32 safely converts int32 value to uint32.
func Int32ToUint32(src int32) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "uint32")
	}
	return uint32(src), nil
}
