// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int32ToByte safely converts int32 value to byte.
func Int32ToByte(src int32) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int32", "byte")
	}
	return byte(src), nil
}
