// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToUint safely converts int32 value to uint.
func Int32ToUint(src int32) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "uint")
	}
	return uint(src), nil
}
