// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Int32ToDuration safely converts int32 value to [time.Duration].
func Int32ToDuration(src int32) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
