// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int32ToUint16 safely converts int32 value to uint16.
func Int32ToUint16(src int32) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int32", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "int32", "uint16")
	}
	return uint16(src), nil
}
