// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int32ToFloat64 safely converts int32 value to float64.
func Int32ToFloat64(src int32) (dst float64, err error) {
	return float64(src), nil
}
