// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToUint8 safely converts int64 value to uint8.
func Int64ToUint8(src int64) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int64", "uint8")
	}
	return uint8(src), nil
}
