// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Int64ToDuration safely converts int64 value to [time.Duration].
func Int64ToDuration(src int64) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
