// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToInt safely converts int64 value to int.
func Int64ToInt(src int64) (dst int, err error) {
	return int(src), nil
}
