// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToInt8 safely converts int64 value to int8.
func Int64ToInt8(src int64) (dst int8, err error) {
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "int64", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "int64", "int8")
	}
	return int8(src), nil
}
