// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToRune safely converts int64 value to rune.
func Int64ToRune(src int64) (dst rune, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "int64", "rune")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "int64", "rune")
	}
	return rune(src), nil
}
