// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_Int64ToFloat64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int64
		want  float64
		err   error
		msg   string
	}{
		{
			"error - safe underflow",
			Float64SafeIntMin - 1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from int64 to float64",
		},
		{
			"error - safe overflow",
			Float64SafeIntMax + 1,
			0,
			ErrInvSafeRange,
			"value out of safe range: from int64 to float64",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Int64ToFloat64(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, int64(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float64(0), have)
		})
	}
}
