// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToInt safely converts an int64 value to int.
func Int64ToInt(src int64) (dst int, err error) {
	if src < math.MinInt {
		return 0, NewError(ErrInvRange, "int64", "int")
	}
	if src > math.MaxInt {
		return 0, NewError(ErrInvRange, "int64", "int")
	}
	return int(src), nil
}
