// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToUint32 safely converts int64 value to uint32.
func Int64ToUint32(src int64) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uint32")
	}
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "int64", "uint32")
	}
	return uint32(src), nil
}
