// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToInt32 safely converts int64 value to int32.
func Int64ToInt32(src int64) (dst int32, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "int64", "int32")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "int64", "int32")
	}
	return int32(src), nil
}
