// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToUint16 safely converts int64 value to uint16.
func Int64ToUint16(src int64) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "int64", "uint16")
	}
	return uint16(src), nil
}
