// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToFloat64 safely converts int64 value to float64.
func Int64ToFloat64(src int64) (dst float64, err error) {
	if src < Float64SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "int64", "float64")
	}
	if src > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "int64", "float64")
	}
	return float64(src), nil
}
