// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToByte safely converts int64 value to byte.
func Int64ToByte(src int64) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int64", "byte")
	}
	return byte(src), nil
}
