// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToFloat32 safely converts int64 value to float32.
func Int64ToFloat32(src int64) (dst float32, err error) {
	if src < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "int64", "float32")
	}
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "int64", "float32")
	}
	return float32(src), nil
}
