// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToUintptr safely converts int64 value to uintptr.
func Int64ToUintptr(src int64) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uintptr")
	}
	return uintptr(src), nil
}
