// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_Int64ToUint8_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int64
		want  uint8
		err   error
		msg   string
	}{
		{
			"error - negative",
			-1,
			0,
			ErrInvRange,
			"value out of range: from int64 to uint8",
		},
		{
			"error - overflow",
			math.MaxUint8 + 1,
			0,
			ErrInvRange,
			"value out of range: from int64 to uint8",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Int64ToUint8(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, int64(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint8(0), have)
		})
	}
}
