// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToUint safely converts int64 value to uint.
func Int64ToUint(src int64) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uint")
	}
	return uint(src), nil
}
