// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int64ToUint64 safely converts int64 value to uint64.
func Int64ToUint64(src int64) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int64", "uint64")
	}
	return uint64(src), nil
}
