// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Int64ToInt16 safely converts int64 value to int16.
func Int64ToInt16(src int64) (dst int16, err error) {
	if src < math.MinInt16 {
		return 0, NewError(ErrInvRange, "int64", "int16")
	}
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "int64", "int16")
	}
	return int16(src), nil
}
