// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Int8ToDuration safely converts int8 value to [time.Duration].
func Int8ToDuration(src int8) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
