// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToInt16 safely converts int8 value to int16.
func Int8ToInt16(src int8) (dst int16, err error) {
	return int16(src), nil
}
