// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToInt8 safely converts int8 value to int8.
func Int8ToInt8(src int8) (dst int8, err error) {
	return src, nil
}
