// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUint16 safely converts int8 value to uint16.
func Int8ToUint16(src int8) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uint16")
	}
	return uint16(src), nil
}
