// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUint32 safely converts int8 value to uint32.
func Int8ToUint32(src int8) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uint32")
	}
	return uint32(src), nil
}
