// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUint64 safely converts int8 value to uint64.
func Int8ToUint64(src int8) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uint64")
	}
	return uint64(src), nil
}
