// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToByte safely converts int8 value to byte.
func Int8ToByte(src int8) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "byte")
	}
	return byte(src), nil
}
