// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUintptr safely converts int8 value to uintptr.
func Int8ToUintptr(src int8) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uintptr")
	}
	return uintptr(src), nil
}
