// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToRune safely converts int8 value to rune.
func Int8ToRune(src int8) (dst rune, err error) {
	return rune(src), nil
}
