// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_Int8ToInt8_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int8
		want  int8
	}{
		{"min", math.MinInt8, math.MinInt8},
		{"max", math.MaxInt8, math.MaxInt8},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Int8ToInt8(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, int8(have))
		})
	}
}
