// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToInt32 safely converts int8 value to int32.
func Int8ToInt32(src int8) (dst int32, err error) {
	return int32(src), nil
}
