// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToFloat64 safely converts int8 value to float64.
func Int8ToFloat64(src int8) (dst float64, err error) {
	return float64(src), nil
}
