// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToInt safely converts int8 value to int.
func Int8ToInt(src int8) (dst int, err error) {
	return int(src), nil
}
