// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUint safely converts int8 value to uint.
func Int8ToUint(src int8) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uint")
	}
	return uint(src), nil
}
