// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToInt64 safely converts int8 value to int64.
func Int8ToInt64(src int8) (dst int64, err error) {
	return int64(src), nil
}
