// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Int8ToUint8 safely converts int8 value to uint8.
func Int8ToUint8(src int8) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int8", "uint8")
	}
	return uint8(src), nil
}
