// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_IntToInt16_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int
		want  int16
		err   error
		msg   string
	}{
		{
			"error - underflow",
			math.MinInt16 - 1,
			0,
			ErrInvRange,
			"value out of range: from int to int16",
		},
		{
			"error - overflow",
			math.MaxInt16 + 1,
			0,
			ErrInvRange,
			"value out of range: from int to int16",
		},
		{"success", 42, 42, nil, ""},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := IntToInt16(tc.value)

			// --- Then ---
			if tc.err == nil {
				assert.NoError(t, err)
				assert.Equal(t, tc.want, have)
				assert.Equal(t, tc.value, int(have))
				return
			}

			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, int16(0), have)
		})
	}
}
