// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToFloat32 safely converts int value to float32.
func IntToFloat32(src int) (dst float32, err error) {
	if src < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "int", "float32")
	}
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "int", "float32")
	}
	return float32(src), nil
}
