// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// IntToDuration safely converts int value to [time.Duration].
func IntToDuration(src int) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
