// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToUint32 safely converts int value to uint32.
func IntToUint32(src int) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "uint32")
	}
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "int", "uint32")
	}
	return uint32(src), nil
}
