// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToInt64 safely converts int value to int64.
func IntToInt64(src int) (dst int64, err error) {
	return int64(src), nil
}
