// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToInt8 safely converts int value to int8.
func IntToInt8(src int) (dst int8, err error) {
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "int", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "int", "int8")
	}
	return int8(src), nil
}
