// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToUint8 safely converts int value to uint8.
func IntToUint8(src int) (dst uint8, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "uint8")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int", "uint8")
	}
	return uint8(src), nil
}
