// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToUint64 safely converts int value to uint64.
func IntToUint64(src int) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "uint64")
	}
	return uint64(src), nil
}
