// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToRune safely converts int value to rune.
func IntToRune(src int) (dst rune, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "int", "rune")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "int", "rune")
	}
	return rune(src), nil
}
