// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToFloat64 safely converts an int value to float64.
func IntToFloat64(src int) (dst float64, err error) {
	if int64(src) < Float64SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "int", "float64")
	}
	if int64(src) > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "int", "float64")
	}
	return float64(src), nil
}
