// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToByte safely converts int value to byte.
func IntToByte(src int) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "int", "byte")
	}
	return byte(src), nil
}
