// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToInt16 safely converts an int value to int16.
func IntToInt16(src int) (dst int16, err error) {
	if int64(src) < math.MinInt16 {
		return 0, NewError(ErrInvRange, "int", "int16")
	}
	if int64(src) > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "int", "int16")
	}
	return int16(src), nil
}
