// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToInt32 safely converts int value to int32.
func IntToInt32(src int) (dst int32, err error) {
	if src < math.MinInt32 {
		return 0, NewError(ErrInvRange, "int", "int32")
	}
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "int", "int32")
	}
	return int32(src), nil
}
