// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToInt safely converts int value to int.
func IntToInt(src int) (dst int, err error) {
	return src, nil
}
