// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToUint16 safely converts int value to uint16.
func IntToUint16(src int) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "int", "uint16")
	}
	return uint16(src), nil
}
