// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"strconv"
	"testing"
)

func Test_IntToRune_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int
		want  rune
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := IntToRune(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, int(have))
		})
	}
}

func Test_IntToRune_64bit_tabular(t *testing.T) {
	if strconv.IntSize != 64 {
		t.Skip("64-bit platforms only")
	}

	tt := []struct {
		testN string

		value int64
		err   error
		msg   string
	}{
		{
			"error - underflow",
			math.MinInt32 - 1,
			ErrInvRange,
			"value out of range: from int to rune",
		},
		{
			"error - overflow",
			math.MaxInt32 + 1,
			ErrInvRange,
			"value out of range: from int to rune",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- Given ---
			src := int(tc.value)

			// --- When ---
			have, err := IntToRune(src)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, rune(0), have)
		})
	}
}
