// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"strconv"
	"testing"
)

func Test_IntToFloat64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int
		want  float64
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := IntToFloat64(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, int(have))
		})
	}
}

func Test_IntToFloat64_64bit_tabular(t *testing.T) {
	if strconv.IntSize != 64 {
		t.Skip("64-bit platforms only")
	}

	tt := []struct {
		testN string

		value int64
		err   error
		msg   string
	}{
		{
			"error - safe underflow",
			Float64SafeIntMin - 1,
			ErrInvSafeRange,
			"value out of safe range: from int to float64",
		},
		{
			"error - safe overflow",
			Float64SafeIntMax + 1,
			ErrInvSafeRange,
			"value out of safe range: from int to float64",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- Given ---
			src := int(tc.value)

			// --- When ---
			have, err := IntToFloat64(src)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float64(0), have)
		})
	}
}
