// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_IntToByte_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int
		want  byte
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := IntToByte(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, int(have))
		})
	}
}

func Test_IntToByte_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value int
		err   error
		msg   string
	}{
		{
			"error - negative",
			-1,
			ErrInvRange,
			"value out of range: from int to byte",
		},
		{
			"error - overflow",
			math.MaxUint8 + 1,
			ErrInvRange,
			"value out of range: from int to byte",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := IntToByte(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, byte(0), have)
		})
	}
}
