// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// IntToUint safely converts int value to uint.
func IntToUint(src int) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "int", "uint")
	}
	return uint(src), nil
}
