// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// IntToRune safely converts an int value to rune.
func IntToRune(src int) (dst rune, err error) {
	if int64(src) < math.MinInt32 {
		return 0, NewError(ErrInvRange, "int", "rune")
	}
	if int64(src) > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "int", "rune")
	}
	return rune(src), nil
}
