// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// RuneToInt16 safely converts rune value to int16.
func RuneToInt16(src rune) (dst int16, err error) {
	if src < math.MinInt16 {
		return 0, NewError(ErrInvRange, "rune", "int16")
	}
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "rune", "int16")
	}
	return int16(src), nil
}
