// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToUint32 safely converts rune value to uint32.
func RuneToUint32(src rune) (dst uint32, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "uint32")
	}
	return uint32(src), nil
}
