// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToUint64 safely converts rune value to uint64.
func RuneToUint64(src rune) (dst uint64, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "uint64")
	}
	return uint64(src), nil
}
