// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// RuneToInt8 safely converts rune value to int8.
func RuneToInt8(src rune) (dst int8, err error) {
	if src < math.MinInt8 {
		return 0, NewError(ErrInvRange, "rune", "int8")
	}
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "rune", "int8")
	}
	return int8(src), nil
}
