// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"testing"
)

func Test_RuneToInt16_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value rune
		want  int16
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := RuneToInt16(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, rune(have))
		})
	}
}

func Test_RuneToInt16_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value rune
		err   error
		msg   string
	}{
		{
			"error - underflow",
			math.MinInt16 - 1,
			ErrInvRange,
			"value out of range: from rune to int16",
		},
		{
			"error - overflow",
			math.MaxInt16 + 1,
			ErrInvRange,
			"value out of range: from rune to int16",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := RuneToInt16(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, int16(0), have)
		})
	}
}
