// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToUint safely converts rune value to uint.
func RuneToUint(src rune) (dst uint, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "uint")
	}
	return uint(src), nil
}
