// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToFloat64 safely converts rune value to float64.
func RuneToFloat64(src rune) (dst float64, err error) {
	return float64(src), nil
}
