// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// RuneToByte safely converts rune value to byte.
func RuneToByte(src rune) (dst byte, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "byte")
	}
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "rune", "byte")
	}
	return byte(src), nil
}
