// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToUintptr safely converts rune value to uintptr.
func RuneToUintptr(src rune) (dst uintptr, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "uintptr")
	}
	return uintptr(src), nil
}
