// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToFloat32 safely converts rune value to float32.
func RuneToFloat32(src rune) (dst float32, err error) {
	if src < Float32SafeIntMin {
		return 0, NewError(ErrInvSafeRange, "rune", "float32")
	}
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "rune", "float32")
	}
	return float32(src), nil
}
