// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// RuneToDuration safely converts rune value to [time.Duration].
func RuneToDuration(src rune) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
