// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToInt64 safely converts rune value to int64.
func RuneToInt64(src rune) (dst int64, err error) {
	return int64(src), nil
}
