// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// RuneToUint16 safely converts rune value to uint16.
func RuneToUint16(src rune) (dst uint16, err error) {
	if src < 0 {
		return 0, NewError(ErrInvRange, "rune", "uint16")
	}
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "rune", "uint16")
	}
	return uint16(src), nil
}
