// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToInt32 safely converts rune value to int32.
func RuneToInt32(src rune) (dst int32, err error) {
	return int32(src), nil
}
