// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// RuneToInt safely converts rune value to int.
func RuneToInt(src rune) (dst int, err error) {
	return int(src), nil
}
