// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintptrToUint safely converts uintptr value to uint.
func UintptrToUint(src uintptr) (dst uint, err error) {
	return uint(src), nil
}
