// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintptrToUint64 safely converts uintptr value to uint64.
func UintptrToUint64(src uintptr) (dst uint64, err error) {
	return uint64(src), nil
}
