// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToUint8 safely converts uint64 value to uint8.
func Uint64ToUint8(src uint64) (dst uint8, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint64", "uint8")
	}
	return uint8(src), nil
}
