// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToInt32 safely converts uint64 value to int32.
func Uint64ToInt32(src uint64) (dst int32, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uint64", "int32")
	}
	return int32(src), nil
}
