// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToUint32 safely converts uint32 value to uint32.
func Uint32ToUint32(src uint32) (dst uint32, err error) {
	return src, nil
}
