// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintToUint64 safely converts uint value to uint64.
func UintToUint64(src uint) (dst uint64, err error) {
	return uint64(src), nil
}
