// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUint64 safely converts uint8 value to uint64.
func Uint8ToUint64(src uint8) (dst uint64, err error) {
	return uint64(src), nil
}
