// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToUint8 safely converts uint value to uint8.
func UintToUint8(src uint) (dst uint8, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint", "uint8")
	}
	return uint8(src), nil
}
