// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToInt32 safely converts uint value to int32.
func UintToInt32(src uint) (dst int32, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uint", "int32")
	}
	return int32(src), nil
}
