// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToInt safely converts uint8 value to int.
func Uint8ToInt(src uint8) (dst int, err error) {
	return int(src), nil
}
