// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUint32 safely converts uint8 value to uint32.
func Uint8ToUint32(src uint8) (dst uint32, err error) {
	return uint32(src), nil
}
