// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint16ToInt16 safely converts uint16 value to int16.
func Uint16ToInt16(src uint16) (dst int16, err error) {
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "uint16", "int16")
	}
	return int16(src), nil
}
