// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToByte safely converts uint value to byte.
func UintToByte(src uint) (dst byte, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint", "byte")
	}
	return byte(src), nil
}
