// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintToFloat32 safely converts uint value to float32.
func UintToFloat32(src uint) (dst float32, err error) {
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uint", "float32")
	}
	return float32(src), nil
}
