// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToUint64 safely converts uint32 value to uint64.
func Uint32ToUint64(src uint32) (dst uint64, err error) {
	return uint64(src), nil
}
