// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToRune safely converts uint32 value to rune.
func Uint32ToRune(src uint32) (dst rune, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uint32", "rune")
	}
	return rune(src), nil
}
