// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToRune safely converts uint8 value to rune.
func Uint8ToRune(src uint8) (dst rune, err error) {
	return rune(src), nil
}
