// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToInt safely converts uintptr value to int.
func UintptrToInt(src uintptr) (dst int, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uintptr", "int")
	}
	return int(src), nil
}
