// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToInt64 safely converts uint32 value to int64.
func Uint32ToInt64(src uint32) (dst int64, err error) {
	return int64(src), nil
}
