// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint64ToFloat64 safely converts uint64 value to float64.
func Uint64ToFloat64(src uint64) (dst float64, err error) {
	if src > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uint64", "float64")
	}
	return float64(src), nil
}
