// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintptrToFloat64 safely converts uintptr value to float64.
func UintptrToFloat64(src uintptr) (dst float64, err error) {
	if src > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uintptr", "float64")
	}
	return float64(src), nil
}
