// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToUint16 safely converts uint value to uint16.
func UintToUint16(src uint) (dst uint16, err error) {
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "uint", "uint16")
	}
	return uint16(src), nil
}
