// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToUint16 safely converts uint16 value to uint16.
func Uint16ToUint16(src uint16) (dst uint16, err error) {
	return src, nil
}
