// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUint safely converts uint8 value to uint.
func Uint8ToUint(src uint8) (dst uint, err error) {
	return uint(src), nil
}
