// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint16ToByte safely converts uint16 value to byte.
func Uint16ToByte(src uint16) (dst byte, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint16", "byte")
	}
	return byte(src), nil
}
