// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToInt8 safely converts uint value to int8.
func UintToInt8(src uint) (dst int8, err error) {
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "uint", "int8")
	}
	return int8(src), nil
}
