// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToInt64 safely converts uint16 value to int64.
func Uint16ToInt64(src uint16) (dst int64, err error) {
	return int64(src), nil
}
