// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToUint32 safely converts uint64 value to uint32.
func Uint64ToUint32(src uint64) (dst uint32, err error) {
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "uint64", "uint32")
	}
	return uint32(src), nil
}
