// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToInt8 safely converts uint32 value to int8.
func Uint32ToInt8(src uint32) (dst int8, err error) {
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "uint32", "int8")
	}
	return int8(src), nil
}
