// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint16ToUint8 safely converts uint16 value to uint8.
func Uint16ToUint8(src uint16) (dst uint8, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint16", "uint8")
	}
	return uint8(src), nil
}
