// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUint8 safely converts uint8 value to uint8.
func Uint8ToUint8(src uint8) (dst uint8, err error) {
	return src, nil
}
