// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// UintToDuration safely converts uint value to [time.Duration].
func UintToDuration(src uint) (dst time.Duration, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint", "time.Duration")
	}
	return time.Duration(src), nil
}
