// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToRune safely converts uint16 value to rune.
func Uint16ToRune(src uint16) (dst rune, err error) {
	return rune(src), nil
}
