// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToFloat32 safely converts uint32 value to float32.
func Uint32ToFloat32(src uint32) (dst float32, err error) {
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uint32", "float32")
	}
	return float32(src), nil
}
