// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Uint32ToDuration safely converts uint32 value to [time.Duration].
func Uint32ToDuration(src uint32) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
