// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToInt safely converts uint value to int.
func UintToInt(src uint) (dst int, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint", "int")
	}
	return int(src), nil
}
