// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintToUintptr safely converts uint value to uintptr.
func UintToUintptr(src uint) (dst uintptr, err error) {
	return uintptr(src), nil
}
