// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToUintptr safely converts uint32 value to uintptr.
func Uint32ToUintptr(src uint32) (dst uintptr, err error) {
	return uintptr(src), nil
}
