// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToByte safely converts uintptr value to byte.
func UintptrToByte(src uintptr) (dst byte, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uintptr", "byte")
	}
	return byte(src), nil
}
