// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// UintptrToDuration safely converts uintptr value to [time.Duration].
func UintptrToDuration(src uintptr) (dst time.Duration, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uintptr", "time.Duration")
	}
	return time.Duration(src), nil
}
