// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToInt8 safely converts uintptr value to int8.
func UintptrToInt8(src uintptr) (dst int8, err error) {
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "uintptr", "int8")
	}
	return int8(src), nil
}
