// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToUint safely converts uint16 value to uint.
func Uint16ToUint(src uint16) (dst uint, err error) {
	return uint(src), nil
}
