// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToUintptr safely converts uint16 value to uintptr.
func Uint16ToUintptr(src uint16) (dst uintptr, err error) {
	return uintptr(src), nil
}
