// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToInt16 safely converts uintptr value to int16.
func UintptrToInt16(src uintptr) (dst int16, err error) {
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "uintptr", "int16")
	}
	return int16(src), nil
}
