// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"strconv"
	"testing"
)

func Test_Uint64ToUint_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value uint64
		want  uint
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Uint64ToUint(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, uint64(have))
		})
	}
}

func Test_Uint64ToUint_32bit_tabular(t *testing.T) {
	if strconv.IntSize != 32 {
		t.Skip("32-bit platforms only")
	}

	tt := []struct {
		testN string

		value uint64
		err   error
		msg   string
	}{
		{
			"error - overflow",
			math.MaxUint32 + 1,
			ErrInvRange,
			"value out of range: from uint64 to uint",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := Uint64ToUint(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, uint(0), have)
		})
	}
}
