// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintToFloat64 safely converts uint value to float64.
func UintToFloat64(src uint) (dst float64, err error) {
	if src > Float64SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uint", "float64")
	}
	return float64(src), nil
}
