// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"testing"
)

func Test_UintToFloat32_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value uint
		want  float32
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := UintToFloat32(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, uint(have))
		})
	}
}

func Test_UintToFloat32_error_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value uint
		err   error
		msg   string
	}{
		{
			"error - safe overflow",
			Float32SafeIntMax + 1,
			ErrInvSafeRange,
			"value out of safe range: from uint to float32",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := UintToFloat32(tc.value)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, float32(0), have)
		})
	}
}
