// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Uint16ToDuration safely converts uint16 value to [time.Duration].
func Uint16ToDuration(src uint16) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
