// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToInt32 safely converts uint8 value to int32.
func Uint8ToInt32(src uint8) (dst int32, err error) {
	return int32(src), nil
}
