// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToInt64 safely converts uint64 value to int64.
func Uint64ToInt64(src uint64) (dst int64, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint64", "int64")
	}
	return int64(src), nil
}
