// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintptrToUintptr safely converts uintptr value to uintptr.
func UintptrToUintptr(src uintptr) (dst uintptr, err error) {
	return src, nil
}
