// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUintptr safely converts uint8 value to uintptr.
func Uint8ToUintptr(src uint8) (dst uintptr, err error) {
	return uintptr(src), nil
}
