// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToFloat64 safely converts uint8 value to float64.
func Uint8ToFloat64(src uint8) (dst float64, err error) {
	return float64(src), nil
}
