// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint64ToFloat32 safely converts uint64 value to float32.
func Uint64ToFloat32(src uint64) (dst float32, err error) {
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uint64", "float32")
	}
	return float32(src), nil
}
