// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToUint safely converts a uint64 value to uint.
func Uint64ToUint(src uint64) (dst uint, err error) {
	if src > math.MaxUint {
		return 0, NewError(ErrInvRange, "uint64", "uint")
	}
	return uint(src), nil
}
