// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToUint16 safely converts uint64 value to uint16.
func Uint64ToUint16(src uint64) (dst uint16, err error) {
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "uint64", "uint16")
	}
	return uint16(src), nil
}
