// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToUint32 safely converts uintptr value to uint32.
func UintptrToUint32(src uintptr) (dst uint32, err error) {
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "uintptr", "uint32")
	}
	return uint32(src), nil
}
