// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToInt32 safely converts uint16 value to int32.
func Uint16ToInt32(src uint16) (dst int32, err error) {
	return int32(src), nil
}
