// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintToUint safely converts uint value to uint.
func UintToUint(src uint) (dst uint, err error) {
	return src, nil
}
