// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToUint32 safely converts uint16 value to uint32.
func Uint16ToUint32(src uint16) (dst uint32, err error) {
	return uint32(src), nil
}
