// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToInt64 safely converts uintptr value to int64.
func UintptrToInt64(src uintptr) (dst int64, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uintptr", "int64")
	}
	return int64(src), nil
}
