// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// UintptrToFloat32 safely converts uintptr value to float32.
func UintptrToFloat32(src uintptr) (dst float32, err error) {
	if src > Float32SafeIntMax {
		return 0, NewError(ErrInvSafeRange, "uintptr", "float32")
	}
	return float32(src), nil
}
