// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToUint16 safely converts uintptr value to uint16.
func UintptrToUint16(src uintptr) (dst uint16, err error) {
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "uintptr", "uint16")
	}
	return uint16(src), nil
}
