// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToInt16 safely converts uint value to int16.
func UintToInt16(src uint) (dst int16, err error) {
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "uint", "int16")
	}
	return int16(src), nil
}
