// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToInt safely converts uint32 value to int.
func Uint32ToInt(src uint32) (dst int, err error) {
	return int(src), nil
}
