// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToByte safely converts uint8 value to byte.
func Uint8ToByte(src uint8) (dst byte, err error) {
	return byte(src), nil
}
