// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint64ToUint safely converts uint64 value to uint.
func Uint64ToUint(src uint64) (dst uint, err error) {
	return uint(src), nil
}
