// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToRune safely converts uint64 value to rune.
func Uint64ToRune(src uint64) (dst rune, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uint64", "rune")
	}
	return rune(src), nil
}
