// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToInt64 safely converts uint value to int64.
func UintToInt64(src uint) (dst int64, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint", "int64")
	}
	return int64(src), nil
}
