// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToByte safely converts uint64 value to byte.
func Uint64ToByte(src uint64) (dst byte, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint64", "byte")
	}
	return byte(src), nil
}
