// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToInt32 safely converts uint32 value to int32.
func Uint32ToInt32(src uint32) (dst int32, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uint32", "int32")
	}
	return int32(src), nil
}
