// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToInt safely converts uint16 value to int.
func Uint16ToInt(src uint16) (dst int, err error) {
	return int(src), nil
}
