// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToUint8 safely converts uintptr value to uint8.
func UintptrToUint8(src uintptr) (dst uint8, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uintptr", "uint8")
	}
	return uint8(src), nil
}
