// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintToUint32 safely converts uint value to uint32.
func UintToUint32(src uint) (dst uint32, err error) {
	if src > math.MaxUint32 {
		return 0, NewError(ErrInvRange, "uint", "uint32")
	}
	return uint32(src), nil
}
