// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToInt16 safely converts uint64 value to int16.
func Uint64ToInt16(src uint64) (dst int16, err error) {
	if src > math.MaxInt16 {
		return 0, NewError(ErrInvRange, "uint64", "int16")
	}
	return int16(src), nil
}
