// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToRune safely converts uintptr value to rune.
func UintptrToRune(src uintptr) (dst rune, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uintptr", "rune")
	}
	return rune(src), nil
}
