// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint32ToUint safely converts uint32 value to uint.
func Uint32ToUint(src uint32) (dst uint, err error) {
	return uint(src), nil
}
