// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToUint8 safely converts uint32 value to uint8.
func Uint32ToUint8(src uint32) (dst uint8, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint32", "uint8")
	}
	return uint8(src), nil
}
