// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToUint16 safely converts uint32 value to uint16.
func Uint32ToUint16(src uint32) (dst uint16, err error) {
	if src > math.MaxUint16 {
		return 0, NewError(ErrInvRange, "uint32", "uint16")
	}
	return uint16(src), nil
}
