// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToInt16 safely converts uint8 value to int16.
func Uint8ToInt16(src uint8) (dst int16, err error) {
	return int16(src), nil
}
