// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToUint16 safely converts uint8 value to uint16.
func Uint8ToUint16(src uint8) (dst uint16, err error) {
	return uint16(src), nil
}
