// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// UintptrToInt32 safely converts uintptr value to int32.
func UintptrToInt32(src uintptr) (dst int32, err error) {
	if src > math.MaxInt32 {
		return 0, NewError(ErrInvRange, "uintptr", "int32")
	}
	return int32(src), nil
}
