// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint16ToFloat64 safely converts uint16 value to float64.
func Uint16ToFloat64(src uint16) (dst float64, err error) {
	return float64(src), nil
}
