// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToInt64 safely converts uint8 value to int64.
func Uint8ToInt64(src uint8) (dst int64, err error) {
	return int64(src), nil
}
