// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"time"
)

// Uint8ToDuration safely converts uint8 value to [time.Duration].
func Uint8ToDuration(src uint8) (dst time.Duration, err error) {
	return time.Duration(src), nil
}
