// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"github.com/ctx42/testing/pkg/assert"
	"math"
	"strconv"
	"testing"
)

func Test_UintptrToInt64_tabular(t *testing.T) {
	tt := []struct {
		testN string

		value uintptr
		want  int64
	}{
		{"success", 42, 42},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- When ---
			have, err := UintptrToInt64(tc.value)

			// --- Then ---
			assert.NoError(t, err)
			assert.Equal(t, tc.want, have)
			assert.Equal(t, tc.value, uintptr(have))
		})
	}
}

func Test_UintptrToInt64_64bit_tabular(t *testing.T) {
	if strconv.IntSize != 64 {
		t.Skip("64-bit platforms only")
	}

	tt := []struct {
		testN string

		value uint64
		err   error
		msg   string
	}{
		{
			"error - overflow",
			math.MaxInt64 + 1,
			ErrInvRange,
			"value out of range: from uintptr to int64",
		},
	}

	for _, tc := range tt {
		t.Run(tc.testN, func(t *testing.T) {
			// --- Given ---
			src := uintptr(tc.value)

			// --- When ---
			have, err := UintptrToInt64(src)

			// --- Then ---
			assert.ErrorIs(t, tc.err, err)
			assert.ErrorEqual(t, tc.msg, err)
			assert.Equal(t, int64(0), have)
		})
	}
}
