// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint16ToInt8 safely converts uint16 value to int8.
func Uint16ToInt8(src uint16) (dst int8, err error) {
	if src > math.MaxInt8 {
		return 0, NewError(ErrInvRange, "uint16", "int8")
	}
	return int8(src), nil
}
