// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
	"time"
)

// Uint64ToDuration safely converts uint64 value to [time.Duration].
func Uint64ToDuration(src uint64) (dst time.Duration, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint64", "time.Duration")
	}
	return time.Duration(src), nil
}
