// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint64ToInt safely converts uint64 value to int.
func Uint64ToInt(src uint64) (dst int, err error) {
	if src > math.MaxInt64 {
		return 0, NewError(ErrInvRange, "uint64", "int")
	}
	return int(src), nil
}
