// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

import (
	"math"
)

// Uint32ToByte safely converts uint32 value to byte.
func Uint32ToByte(src uint32) (dst byte, err error) {
	if src > math.MaxUint8 {
		return 0, NewError(ErrInvRange, "uint32", "byte")
	}
	return byte(src), nil
}
