// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

// Code generated by 00_generate_main.go. DO NOT EDIT.

package convert

// Uint8ToFloat32 safely converts uint8 value to float32.
func Uint8ToFloat32(src uint8) (dst float32, err error) {
	return float32(src), nil
}
