// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ctx42/convert/pkg/codegen"
)

// copyright represents the standard copyright header for generated files.
const copyright = "" +
	"// SPDX-FileCopyrightText: (c) %d Rafal Zajac\n" +
	"// SPDX-License-Identifier: MIT\n\n"

// generatedBy represents the standard generated by header for generated files.
const generatedBy = "// Code generated by 00_generate_main.go. DO NOT EDIT.\n\n"

// The verbose prints generated file names to stdout when set to true.
//
// Set the VERBOSE environment variable to enable verbose mode.
var verbose bool

// main generates conversion functions.
func main() {
	cwd, err := os.Getwd()
	if err != nil {
		_, _ = fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}

	_, verbose = os.LookupEnv("VERBOSE")

	pkgName := "convert"
	pkgPath := filepath.Join(cwd, "../../pkg", pkgName)
	pkgPath = filepath.Clean(pkgPath)
	if err = generateNumericConverters(pkgName, pkgPath); err != nil {
		_, _ = fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}

	pkgPath = filepath.Join(cwd, "../../pkg", pkgName)
	pkgPath = filepath.Clean(pkgPath)
	if err = generateAnyToNumericConverters(pkgName, pkgPath); err != nil {
		_, _ = fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}

	if err = generateRegister(pkgName, pkgPath); err != nil {
		_, _ = fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}
}

// generateNumericConverters writes a conversion function file and its test
// file to pkgPath for every pair of numericTypes.
func generateNumericConverters(pkgName, pkgPath string) error {
	opts := []codegen.Option{
		codegen.WithCopyright(fmt.Sprintf(copyright, time.Now().Year())),
		codegen.WithGeneratedBy(generatedBy),
	}

	gen := codegen.NewGenSrcToDst(pkgName, opts...)
	nts := numericTypes()
	buf := &bytes.Buffer{}

	for _, src := range nts {
		for _, dst := range nts {
			buf.Reset()
			if err := gen.GenerateCode(buf, src, dst); err != nil {
				return err
			}

			srcName := strings.ToLower(src.Name())
			dstName := strings.ToLower(dst.Name())
			file := fmt.Sprintf("%s_to_%s.go", srcName, dstName)
			pth := filepath.Join(pkgPath, file)

			if verbose {
				fmt.Printf(" %s\n", pth)
			}
			if err := os.WriteFile(pth, buf.Bytes(), 0644); err != nil {
				return err
			}

			buf.Reset()
			if err := gen.GenerateTest(buf, src, dst); err != nil {
				return err
			}

			file = fmt.Sprintf("%s_to_%s_test.go", srcName, dstName)
			pth = filepath.Join(pkgPath, file)
			if verbose {
				fmt.Printf(" %s\n", pth)
			}
			if err := os.WriteFile(pth, buf.Bytes(), 0644); err != nil {
				return err
			}
		}
	}
	return nil
}

// generateAnyToNumericConverters writes an AnyToX function file and its test
// file to pkgPath for every one of numericTypes.
func generateAnyToNumericConverters(pkgName, pkgPath string) error {
	opts := []codegen.Option{
		codegen.WithCopyright(fmt.Sprintf(copyright, time.Now().Year())),
		codegen.WithGeneratedBy(generatedBy),
	}

	gen := codegen.NewGenAnyToDst(pkgName, opts...)
	nts := numericTypes()
	buf := &bytes.Buffer{}

	for _, dst := range nts {
		buf.Reset()
		if err := gen.GenerateCode(buf, dst); err != nil {
			return err
		}

		dstName := strings.ToLower(dst.Name())
		file := fmt.Sprintf("any_to_%s.go", dstName)
		pth := filepath.Join(pkgPath, file)
		if verbose {
			fmt.Printf(" %s\n", pth)
		}
		if err := os.WriteFile(pth, buf.Bytes(), 0644); err != nil {
			return err
		}

		buf.Reset()
		if err := gen.GenerateTest(buf, dst); err != nil {
			return err
		}

		file = fmt.Sprintf("any_to_%s_test.go", dstName)
		pth = filepath.Join(pkgPath, file)
		if verbose {
			fmt.Printf(" %s\n", pth)
		}
		if err := os.WriteFile(pth, buf.Bytes(), 0644); err != nil {
			return err
		}
	}
	return nil
}

// generateRegister writes the file with the function registering the
// converters between every pair of numericTypes, except the byte and rune
// aliases. They are identical to uint8 and int32, so their converters would
// only replace ones already registered for the same type pair.
func generateRegister(pkgName, pkgPath string) error {
	opts := []codegen.Option{
		codegen.WithCopyright(fmt.Sprintf(copyright, time.Now().Year())),
		codegen.WithGeneratedBy(generatedBy),
	}

	var types []codegen.Type
	for _, typ := range numericTypes() {
		if typ.Code() == "byte" || typ.Code() == "rune" {
			continue
		}
		types = append(types, typ)
	}

	buf := &bytes.Buffer{}
	gen := codegen.NewGenRegister(pkgName, opts...)
	if err := gen.GenerateCode(buf, types); err != nil {
		return err
	}

	pth := filepath.Join(pkgPath, "numeric_register.go")
	if verbose {
		fmt.Printf(" %s\n", pth)
	}
	return os.WriteFile(pth, buf.Bytes(), 0644)
}

// numericTypes returns the numeric types, including aliases, for which
// converters are generated.
func numericTypes() []codegen.Type {
	return []codegen.Type{
		codegen.NumericType[int](),
		codegen.NumericType[int8](),
		codegen.NumericType[int16](),
		codegen.NumericType[int32](),
		codegen.NumericType[int64](),
		codegen.NumericType[uint](),
		codegen.NumericType[uint8](),
		codegen.NumericType[uint16](),
		codegen.NumericType[uint32](),
		codegen.NumericType[uint64](),
		codegen.NumericType[uintptr](),
		codegen.NumericType[float32](),
		codegen.NumericType[float64](),
		codegen.NumericType[uint8]().Alias("byte"),
		codegen.NumericType[int32]().Alias("rune"),
		codegen.NumericType[int64]().Alias("time", "Duration"),
	}
}
