// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac <rzajac@gmail.com>
// SPDX-License-Identifier: MIT

package codegen

import (
	"bytes"
	"testing"

	"github.com/ctx42/testing/pkg/assert"
	"github.com/ctx42/testing/pkg/goldy"
)

func Test_file_writeCode(t *testing.T) {
	// --- Given ---
	fil := newFile("pkg")

	// --- When ---
	fil.writeCode("%s", "abc")

	// --- Then ---
	assert.Equal(t, "pkg", fil.pkg)
	assert.Equal(t, "abc", fil.code.String())
	assert.Len(t, 0, fil.imps)
}

func Test_file_addImport(t *testing.T) {
	// --- Given ---
	fil := newFile("pkg")

	// --- When ---
	fil.addImport("", "abc", "", "abc")

	// --- Then ---
	assert.Equal(t, []string{"", "abc", "", "abc"}, fil.imps)
}

func Test_file_renderImports(t *testing.T) {
	t.Run("without imports", func(t *testing.T) {
		// --- Given ---
		fil := newFile("pkg")

		// --- When ---
		have := fil.renderImports()

		// --- Then ---
		assert.Empty(t, fil.code.String())
		assert.Empty(t, have)
	})

	t.Run("with imports", func(t *testing.T) {
		// --- Given ---
		fil := newFile("pkg")
		fil.addImport("xyz", "abc")

		// --- When ---
		have := fil.renderImports()

		// --- Then ---
		assert.Empty(t, fil.code.String())

		want := "import (\n\t\"abc\"\n\t\"xyz\"\n)\n\n"
		assert.Equal(t, want, have)
	})

	t.Run("empty import strings are removed", func(t *testing.T) {
		// --- Given ---
		fil := newFile("pkg")
		fil.addImport("", "abc", "", "xyz")

		// --- When ---
		have := fil.renderImports()

		// --- Then ---
		assert.Empty(t, fil.code.String())

		want := "import (\n\t\"abc\"\n\t\"xyz\"\n)\n\n"
		assert.Equal(t, want, have)
	})

	t.Run("imports are sorted alphabetically ", func(t *testing.T) {
		// --- Given ---
		fil := newFile("pkg")
		fil.addImport("xyz", "abc")

		// --- When ---
		have := fil.renderImports()

		// --- Then ---
		assert.Empty(t, fil.code.String())

		want := "import (\n\t\"abc\"\n\t\"xyz\"\n)\n\n"
		assert.Equal(t, want, have)
	})
}

func Test_file_reset(t *testing.T) {
	// --- Given ---
	fil := newFile("pkg")
	fil.writeCode("abc")
	fil.addImport("xyz")

	// --- When ---
	fil.reset()

	// --- Then ---
	assert.Equal(t, "pkg", fil.pkg)
	assert.Empty(t, fil.imps)
	assert.Empty(t, fil.code.String())
}

func Test_file_WriteTo(t *testing.T) {
	t.Run("all file parts written", func(t *testing.T) {
		// --- Given ---
		fil := newFile(
			"pkg",
			WithCopyright("// copyright.\n"),
			WithGeneratedBy("// generated by.\n"),
		)
		fil.addImport("time", "", "math", "")
		fil.writeCode("%s", "func my() {}")
		buf := &bytes.Buffer{}

		// --- When ---
		have, err := fil.WriteTo(buf)

		// --- Then ---
		assert.NoError(t, err)
		assert.Equal(t, int64(84), have)

		gld := goldy.Open(t, "testdata/file_write_to.gld")
		assert.Equal(t, gld.String(), buf.String())
	})
}
