// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

package codegen

// Option represents an option.
type Option func(*Options)

// Options represents code generation options.
type Options struct {
	copyright   string // Copyright header.
	generatedBy string // Line informing code was generated.
	verbose     bool   // Verbose mode.
}

// NewOptions returns a new instance of [Options].
func NewOptions(opts ...Option) Options {
	ops := Options{}
	for _, opt := range opts {
		opt(&ops)
	}
	return ops
}

// WithCopyright is an [Option] for setting the copyright file header.
func WithCopyright(copyright string) Option {
	return func(ops *Options) { ops.copyright = copyright }
}

// WithGeneratedBy is an [Option] for setting the generated by line.
func WithGeneratedBy(by string) Option {
	return func(ops *Options) { ops.generatedBy = by }
}

// WithVerbose is an [Option] turning on verbose mode.
func WithVerbose(ops *Options) { ops.verbose = true }
